---
- name: Wait for instances to become reachable
  hosts: dcos_all
  gather_facts: no
  tasks:
    - name: Wait for instances to become reachable
      wait_for_connection:
        delay: 10
        sleep: 10
        timeout: 120

- name: Collect DC/OS versions
  hosts: dcos_all
  tasks:
    - name: Collect DC/OS versions
      setup:

- name: DC/OS Requirements
  hosts: dcos_all
  become: true
  tasks:
    - include_role:
        name: DCOS.requirements
    - include_role:
        name: DCOS.gpu

- name: "Setup and configure BOOTSTRAP nodes"
  hosts: dcos_bootstraps
  become: true
  tasks:
    - include_role:
        name: DCOS.bootstrap

- name: "Setup and configure MASTER nodes"
  hosts: dcos_masters
  serial: 1
  become: true
  tasks:
    - include_role:
        name: DCOS.master

- name: "Setup and configure AGENT nodes"
  hosts: dcos_agents
  become: true
  tasks:
    - include_role:
        name: DCOS.agent
